/* Inventário inicial da posse v2o. Frases resumidas, ainda sujeitas à revisão jurídica e
   semântica. IDs independem do nome do órgão que receberá o trabalho.
   Recriar com: node tools/import-posse-work.mjs */
/** @typedef {{ id: string, label: string, office: string, source: string }} Competency */
/** @type {ReadonlyArray<Competency>} */
export const COMPETENCIES = [
  {
    id: "casa-civil-coordenacao-dos-ministerios",
    label: "coordenação dos ministérios",
    office: "casa-civil",
    source: "posse-v2o",
  },
  {
    id: "casa-civil-analise-das-propostas-e-dos-atos-do-presidente",
    label: "análise das propostas e dos atos do Presidente",
    office: "casa-civil",
    source: "posse-v2o",
  },
  {
    id: "casa-civil-monitoramento-das-acoes-do-governo",
    label: "monitoramento das ações do governo",
    office: "casa-civil",
    source: "posse-v2o",
  },
  {
    id: "casa-civil-parcerias-de-investimento-e-obras-de-infraestrutura",
    label: "parcerias de investimento e obras de infraestrutura",
    office: "casa-civil",
    source: "posse-v2o",
  },
  {
    id: "fazenda-moeda-credito-e-bancos",
    label: "moeda, crédito e bancos",
    office: "fazenda",
    source: "posse-v2o",
  },
  {
    id: "fazenda-impostos-e-arrecadacao",
    label: "impostos e arrecadação",
    office: "fazenda",
    source: "posse-v2o",
  },
  {
    id: "fazenda-contas-e-divida-publica",
    label: "contas e dívida pública",
    office: "fazenda",
    source: "posse-v2o",
  },
  {
    id: "fazenda-precos-e-tarifas-publicas",
    label: "preços e tarifas públicas",
    office: "fazenda",
    source: "posse-v2o",
  },
  {
    id: "fazenda-fiscalizacao-do-comercio-exterior",
    label: "fiscalização do comércio exterior",
    office: "fazenda",
    source: "posse-v2o",
  },
  {
    id: "planejamento-e-orcamento-orcamento-federal-plano-plurianual-ldo-e-lei-orcamentaria",
    label: "orçamento federal (plano plurianual, LDO e lei orçamentária)",
    office: "planejamento-e-orcamento",
    source: "posse-v2o",
  },
  {
    id: "planejamento-e-orcamento-avaliacao-de-politicas-publicas",
    label: "avaliação de políticas públicas",
    office: "planejamento-e-orcamento",
    source: "posse-v2o",
  },
  {
    id: "planejamento-e-orcamento-financiamentos-de-organismos-internacionais",
    label: "financiamentos de organismos internacionais",
    office: "planejamento-e-orcamento",
    source: "posse-v2o",
  },
  {
    id: "relacoes-institucionais-coordenacao-politica-do-governo",
    label: "coordenação política do governo",
    office: "relacoes-institucionais",
    source: "posse-v2o",
  },
  {
    id: "relacoes-institucionais-relacao-com-estados-e-municipios",
    label: "relação com estados e municípios",
    office: "relacoes-institucionais",
    source: "posse-v2o",
  },
  {
    id: "relacoes-institucionais-conselho-de-desenvolvimento-economico-social-sustentavel",
    label: "Conselho de Desenvolvimento Econômico Social Sustentável",
    office: "relacoes-institucionais",
    source: "posse-v2o",
  },
  {
    id: "justica-e-seguranca-publica-policia-federal-e-seguranca-publica",
    label: "Polícia Federal e segurança pública",
    office: "justica-e-seguranca-publica",
    source: "posse-v2o",
  },
  {
    id: "justica-e-seguranca-publica-politica-judiciaria-e-acesso-a-justica",
    label: "política judiciária e acesso à justiça",
    office: "justica-e-seguranca-publica",
    source: "posse-v2o",
  },
  {
    id: "justica-e-seguranca-publica-defesa-do-consumidor",
    label: "defesa do consumidor",
    office: "justica-e-seguranca-publica",
    source: "posse-v2o",
  },
  {
    id: "justica-e-seguranca-publica-migracoes-e-refugio",
    label: "migrações e refúgio",
    office: "justica-e-seguranca-publica",
    source: "posse-v2o",
  },
  {
    id: "justica-e-seguranca-publica-combate-a-corrupcao-e-a-lavagem-de-dinheiro",
    label: "combate à corrupção e à lavagem de dinheiro",
    office: "justica-e-seguranca-publica",
    source: "posse-v2o",
  },
  {
    id: "defesa-direcao-das-forcas-armadas",
    label: "direção das Forças Armadas",
    office: "defesa",
    source: "posse-v2o",
  },
  {
    id: "defesa-politica-de-defesa",
    label: "política de defesa",
    office: "defesa",
    source: "posse-v2o",
  },
  {
    id: "defesa-servico-militar",
    label: "serviço militar",
    office: "defesa",
    source: "posse-v2o",
  },
  {
    id: "defesa-protecao-da-amazonia-sipam",
    label: "proteção da Amazônia (Sipam)",
    office: "defesa",
    source: "posse-v2o",
  },
  {
    id: "defesa-defesa-cibernetica",
    label: "defesa cibernética",
    office: "defesa",
    source: "posse-v2o",
  },
  {
    id: "saude-coordenacao-do-sus",
    label: "coordenação do SUS",
    office: "saude",
    source: "posse-v2o",
  },
  {
    id: "saude-vigilancia-em-saude-e-sanitaria",
    label: "vigilância em saúde e sanitária",
    office: "saude",
    source: "posse-v2o",
  },
  {
    id: "saude-insumos-e-medicamentos",
    label: "insumos e medicamentos",
    office: "saude",
    source: "posse-v2o",
  },
  {
    id: "saude-pesquisa-em-saude",
    label: "pesquisa em saúde",
    office: "saude",
    source: "posse-v2o",
  },
  {
    id: "educacao-educacao-basica",
    label: "educação básica",
    office: "educacao",
    source: "posse-v2o",
  },
  {
    id: "educacao-universidades-e-pesquisa",
    label: "universidades e pesquisa",
    office: "educacao",
    source: "posse-v2o",
  },
  {
    id: "educacao-avaliacao-educacional",
    label: "avaliação educacional",
    office: "educacao",
    source: "posse-v2o",
  },
  {
    id: "educacao-professores",
    label: "professores",
    office: "educacao",
    source: "posse-v2o",
  },
  {
    id: "educacao-apoio-a-familias-pobres-para-manter-os-filhos-na-escola",
    label: "apoio a famílias pobres para manter os filhos na escola",
    office: "educacao",
    source: "posse-v2o",
  },
  {
    id: "secretaria-geral-relacao-com-os-movimentos-sociais",
    label: "relação com os movimentos sociais",
    office: "secretaria-geral",
    source: "posse-v2o",
  },
  {
    id: "secretaria-geral-participacao-social-e-consultas-populares",
    label: "participação social e consultas populares",
    office: "secretaria-geral",
    source: "posse-v2o",
  },
  {
    id: "secretaria-geral-politicas-para-a-juventude",
    label: "políticas para a juventude",
    office: "secretaria-geral",
    source: "posse-v2o",
  },
  {
    id: "comunicacao-social-comunicacao-e-publicidade-do-governo",
    label: "comunicação e publicidade do governo",
    office: "comunicacao-social",
    source: "posse-v2o",
  },
  {
    id: "comunicacao-social-relacao-com-a-imprensa",
    label: "relação com a imprensa",
    office: "comunicacao-social",
    source: "posse-v2o",
  },
  {
    id: "comunicacao-social-pesquisas-de-opiniao",
    label: "pesquisas de opinião",
    office: "comunicacao-social",
    source: "posse-v2o",
  },
  {
    id: "comunicacao-social-rede-obrigatoria-de-radio-e-tv",
    label: "rede obrigatória de rádio e TV",
    office: "comunicacao-social",
    source: "posse-v2o",
  },
  {
    id: "seguranca-institucional-seguranca-do-presidente-e-do-vice",
    label: "segurança do Presidente e do Vice",
    office: "seguranca-institucional",
    source: "posse-v2o",
  },
  {
    id: "seguranca-institucional-prevencao-de-crises",
    label: "prevenção de crises",
    office: "seguranca-institucional",
    source: "posse-v2o",
  },
  {
    id: "seguranca-institucional-seguranca-da-informacao",
    label: "segurança da informação",
    office: "seguranca-institucional",
    source: "posse-v2o",
  },
  {
    id: "seguranca-institucional-protecao-do-programa-nuclear",
    label: "proteção do programa nuclear",
    office: "seguranca-institucional",
    source: "posse-v2o",
  },
  {
    id: "seguranca-institucional-terrorismo-e-infraestruturas-criticas",
    label: "terrorismo e infraestruturas críticas",
    office: "seguranca-institucional",
    source: "posse-v2o",
  },
  {
    id: "advocacia-geral-da-uniao-defesa-da-uniao-na-justica",
    label: "defesa da União na Justiça",
    office: "advocacia-geral-da-uniao",
    source: "posse-v2o",
  },
  {
    id: "advocacia-geral-da-uniao-consultoria-juridica-ao-presidente",
    label: "consultoria jurídica ao Presidente",
    office: "advocacia-geral-da-uniao",
    source: "posse-v2o",
  },
  {
    id: "agricultura-e-pecuaria-politica-agricola-e-seguro-rural",
    label: "política agrícola e seguro rural",
    office: "agricultura-e-pecuaria",
    source: "posse-v2o",
  },
  {
    id: "agricultura-e-pecuaria-defesa-agropecuaria",
    label: "defesa agropecuária",
    office: "agricultura-e-pecuaria",
    source: "posse-v2o",
  },
  {
    id: "agricultura-e-pecuaria-pesquisa-agropecuaria",
    label: "pesquisa agropecuária",
    office: "agricultura-e-pecuaria",
    source: "posse-v2o",
  },
  {
    id: "agricultura-e-pecuaria-precos-minimos-e-abastecimento",
    label: "preços mínimos e abastecimento",
    office: "agricultura-e-pecuaria",
    source: "posse-v2o",
  },
  {
    id: "agricultura-e-pecuaria-assistencia-tecnica-rural",
    label: "assistência técnica rural",
    office: "agricultura-e-pecuaria",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-industria-politica-industrial",
    label: "política industrial",
    office: "desenvolvimento-industria",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-industria-comercio-exterior",
    label: "comércio exterior",
    office: "desenvolvimento-industria",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-industria-propriedade-intelectual",
    label: "propriedade intelectual",
    office: "desenvolvimento-industria",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-industria-defesa-comercial",
    label: "defesa comercial",
    office: "desenvolvimento-industria",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-industria-economia-verde",
    label: "economia verde",
    office: "desenvolvimento-industria",
    source: "posse-v2o",
  },
  {
    id: "previdencia-social-previdencia-social",
    label: "previdência social",
    office: "previdencia-social",
    source: "posse-v2o",
  },
  {
    id: "previdencia-social-previdencia-complementar",
    label: "previdência complementar",
    office: "previdencia-social",
    source: "posse-v2o",
  },
  {
    id: "cidades-desenvolvimento-urbano",
    label: "desenvolvimento urbano",
    office: "cidades",
    source: "posse-v2o",
  },
  {
    id: "cidades-habitacao",
    label: "habitação",
    office: "cidades",
    source: "posse-v2o",
  },
  {
    id: "cidades-saneamento",
    label: "saneamento",
    office: "cidades",
    source: "posse-v2o",
  },
  {
    id: "cidades-mobilidade-urbana",
    label: "mobilidade urbana",
    office: "cidades",
    source: "posse-v2o",
  },
  {
    id: "cultura-politica-de-cultura-e-artes",
    label: "política de cultura e artes",
    office: "cultura",
    source: "posse-v2o",
  },
  {
    id: "cultura-patrimonio-historico",
    label: "patrimônio histórico",
    office: "cultura",
    source: "posse-v2o",
  },
  {
    id: "cultura-direitos-autorais",
    label: "direitos autorais",
    office: "cultura",
    source: "posse-v2o",
  },
  {
    id: "cultura-economia-criativa",
    label: "economia criativa",
    office: "cultura",
    source: "posse-v2o",
  },
  {
    id: "cultura-diversidade-e-acessibilidade-cultural",
    label: "diversidade e acessibilidade cultural",
    office: "cultura",
    source: "posse-v2o",
  },
  {
    id: "ciencia-tecnologia-e-inovacao-ciencia-tecnologia-e-inovacao",
    label: "ciência, tecnologia e inovação",
    office: "ciencia-tecnologia-e-inovacao",
    source: "posse-v2o",
  },
  {
    id: "ciencia-tecnologia-e-inovacao-transformacao-digital",
    label: "transformação digital",
    office: "ciencia-tecnologia-e-inovacao",
    source: "posse-v2o",
  },
  {
    id: "ciencia-tecnologia-e-inovacao-politica-espacial-e-nuclear",
    label: "política espacial e nuclear",
    office: "ciencia-tecnologia-e-inovacao",
    source: "posse-v2o",
  },
  {
    id: "ciencia-tecnologia-e-inovacao-biosseguranca",
    label: "biossegurança",
    office: "ciencia-tecnologia-e-inovacao",
    source: "posse-v2o",
  },
  {
    id: "comunicacoes-telecomunicacoes",
    label: "telecomunicações",
    office: "comunicacoes",
    source: "posse-v2o",
  },
  {
    id: "comunicacoes-radio-e-tv",
    label: "rádio e TV",
    office: "comunicacoes",
    source: "posse-v2o",
  },
  {
    id: "comunicacoes-inclusao-digital",
    label: "inclusão digital",
    office: "comunicacoes",
    source: "posse-v2o",
  },
  {
    id: "comunicacoes-servicos-postais",
    label: "serviços postais",
    office: "comunicacoes",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-agrario-reforma-agraria",
    label: "reforma agrária",
    office: "desenvolvimento-agrario",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-agrario-apoio-a-agricultura-familiar",
    label: "apoio à agricultura familiar",
    office: "desenvolvimento-agrario",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-agrario-terras-de-comunidades-tradicionais",
    label: "terras de comunidades tradicionais",
    office: "desenvolvimento-agrario",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-agrario-compras-publicas-de-alimentos",
    label: "compras públicas de alimentos",
    office: "desenvolvimento-agrario",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-agrario-assistencia-tecnica-a-agricultura-familiar",
    label: "assistência técnica à agricultura familiar",
    office: "desenvolvimento-agrario",
    source: "posse-v2o",
  },
  {
    id: "integracao-e-desenvolvimento-regional-desenvolvimento-regional",
    label: "desenvolvimento regional",
    office: "integracao-e-desenvolvimento-regional",
    source: "posse-v2o",
  },
  {
    id: "integracao-e-desenvolvimento-regional-defesa-civil",
    label: "defesa civil",
    office: "integracao-e-desenvolvimento-regional",
    source: "posse-v2o",
  },
  {
    id: "integracao-e-desenvolvimento-regional-irrigacao",
    label: "irrigação",
    office: "integracao-e-desenvolvimento-regional",
    source: "posse-v2o",
  },
  {
    id: "integracao-e-desenvolvimento-regional-fundos-de-desenvolvimento-regional",
    label: "fundos de desenvolvimento regional",
    office: "integracao-e-desenvolvimento-regional",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-social-assistencia-social",
    label: "assistência social",
    office: "desenvolvimento-social",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-social-transferencia-de-renda",
    label: "transferência de renda",
    office: "desenvolvimento-social",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-social-seguranca-alimentar-e-combate-a-fome",
    label: "segurança alimentar e combate à fome",
    office: "desenvolvimento-social",
    source: "posse-v2o",
  },
  {
    id: "desenvolvimento-social-reducao-do-uso-abusivo-de-alcool-e-drogas",
    label: "redução do uso abusivo de álcool e drogas",
    office: "desenvolvimento-social",
    source: "posse-v2o",
  },
  {
    id: "direitos-humanos-promocao-dos-direitos-humanos",
    label: "promoção dos direitos humanos",
    office: "direitos-humanos",
    source: "posse-v2o",
  },
  {
    id: "direitos-humanos-ouvidoria-de-direitos-humanos",
    label: "ouvidoria de direitos humanos",
    office: "direitos-humanos",
    source: "posse-v2o",
  },
  {
    id: "direitos-humanos-educacao-em-direitos-humanos",
    label: "educação em direitos humanos",
    office: "direitos-humanos",
    source: "posse-v2o",
  },
  {
    id: "direitos-humanos-combate-a-violencia-e-a-discriminacao",
    label: "combate à violência e à discriminação",
    office: "direitos-humanos",
    source: "posse-v2o",
  },
  {
    id: "empreendedorismo-empreendedorismo",
    label: "empreendedorismo",
    office: "empreendedorismo",
    source: "posse-v2o",
  },
  {
    id: "empreendedorismo-micro-e-pequenas-empresas",
    label: "micro e pequenas empresas",
    office: "empreendedorismo",
    source: "posse-v2o",
  },
  {
    id: "esporte-politica-de-esporte",
    label: "política de esporte",
    office: "esporte",
    source: "posse-v2o",
  },
  {
    id: "esporte-incentivo-ao-esporte",
    label: "incentivo ao esporte",
    office: "esporte",
    source: "posse-v2o",
  },
  {
    id: "esporte-intercambio-esportivo",
    label: "intercâmbio esportivo",
    office: "esporte",
    source: "posse-v2o",
  },
  {
    id: "gestao-e-inovacao-gestao-de-pessoas-do-governo",
    label: "gestão de pessoas do governo",
    office: "gestao-e-inovacao",
    source: "posse-v2o",
  },
  {
    id: "gestao-e-inovacao-transformacao-digital-dos-servicos",
    label: "transformação digital dos serviços",
    office: "gestao-e-inovacao",
    source: "posse-v2o",
  },
  {
    id: "gestao-e-inovacao-imoveis-da-uniao",
    label: "imóveis da União",
    office: "gestao-e-inovacao",
    source: "posse-v2o",
  },
  {
    id: "gestao-e-inovacao-governanca-das-estatais",
    label: "governança das estatais",
    office: "gestao-e-inovacao",
    source: "posse-v2o",
  },
  {
    id: "gestao-e-inovacao-cadastro-ambiental-rural",
    label: "Cadastro Ambiental Rural",
    office: "gestao-e-inovacao",
    source: "posse-v2o",
  },
  {
    id: "igualdade-racial-igualdade-racial-e-acoes-afirmativas",
    label: "igualdade racial e ações afirmativas",
    office: "igualdade-racial",
    source: "posse-v2o",
  },
  {
    id: "igualdade-racial-combate-ao-racismo",
    label: "combate ao racismo",
    office: "igualdade-racial",
    source: "posse-v2o",
  },
  {
    id: "igualdade-racial-quilombolas-e-comunidades-tradicionais",
    label: "quilombolas e comunidades tradicionais",
    office: "igualdade-racial",
    source: "posse-v2o",
  },
  {
    id: "meio-ambiente-politica-ambiental",
    label: "política ambiental",
    office: "meio-ambiente",
    source: "posse-v2o",
  },
  {
    id: "meio-ambiente-mudanca-do-clima",
    label: "mudança do clima",
    office: "meio-ambiente",
    source: "posse-v2o",
  },
  {
    id: "meio-ambiente-florestas-e-vegetacao-nativa",
    label: "florestas e vegetação nativa",
    office: "meio-ambiente",
    source: "posse-v2o",
  },
  {
    id: "meio-ambiente-amazonia-e-demais-biomas",
    label: "Amazônia e demais biomas",
    office: "meio-ambiente",
    source: "posse-v2o",
  },
  {
    id: "meio-ambiente-especies-ameacadas",
    label: "espécies ameaçadas",
    office: "meio-ambiente",
    source: "posse-v2o",
  },
  {
    id: "minas-e-energia-petroleo-gas-e-combustiveis",
    label: "petróleo, gás e combustíveis",
    office: "minas-e-energia",
    source: "posse-v2o",
  },
  {
    id: "minas-e-energia-energia-eletrica",
    label: "energia elétrica",
    office: "minas-e-energia",
    source: "posse-v2o",
  },
  {
    id: "minas-e-energia-mineracao",
    label: "mineração",
    office: "minas-e-energia",
    source: "posse-v2o",
  },
  {
    id: "minas-e-energia-tarifas-de-energia",
    label: "tarifas de energia",
    office: "minas-e-energia",
    source: "posse-v2o",
  },
  {
    id: "minas-e-energia-outorgas-de-minas-e-energia",
    label: "outorgas de minas e energia",
    office: "minas-e-energia",
    source: "posse-v2o",
  },
  {
    id: "mulheres-politicas-para-as-mulheres",
    label: "políticas para as mulheres",
    office: "mulheres",
    source: "posse-v2o",
  },
  {
    id: "mulheres-campanhas-contra-a-discriminacao",
    label: "campanhas contra a discriminação",
    office: "mulheres",
    source: "posse-v2o",
  },
  {
    id: "mulheres-acoes-afirmativas-para-mulheres",
    label: "ações afirmativas para mulheres",
    office: "mulheres",
    source: "posse-v2o",
  },
  {
    id: "pesca-e-aquicultura-politica-de-pesca-e-aquicultura",
    label: "política de pesca e aquicultura",
    office: "pesca-e-aquicultura",
    source: "posse-v2o",
  },
  {
    id: "pesca-e-aquicultura-licencas-de-pesca",
    label: "licenças de pesca",
    office: "pesca-e-aquicultura",
    source: "posse-v2o",
  },
  {
    id: "pesca-e-aquicultura-registro-dos-pescadores",
    label: "registro dos pescadores",
    office: "pesca-e-aquicultura",
    source: "posse-v2o",
  },
  {
    id: "pesca-e-aquicultura-terminais-pesqueiros",
    label: "terminais pesqueiros",
    office: "pesca-e-aquicultura",
    source: "posse-v2o",
  },
  {
    id: "portos-e-aeroportos-portos-e-vias-navegaveis",
    label: "portos e vias navegáveis",
    office: "portos-e-aeroportos",
    source: "posse-v2o",
  },
  {
    id: "portos-e-aeroportos-marinha-mercante",
    label: "marinha mercante",
    office: "portos-e-aeroportos",
    source: "posse-v2o",
  },
  {
    id: "portos-e-aeroportos-aviacao-civil-e-aeroportos",
    label: "aviação civil e aeroportos",
    office: "portos-e-aeroportos",
    source: "posse-v2o",
  },
  {
    id: "povos-indigenas-politica-indigenista",
    label: "política indigenista",
    office: "povos-indigenas",
    source: "posse-v2o",
  },
  {
    id: "povos-indigenas-terras-indigenas",
    label: "terras indígenas",
    office: "povos-indigenas",
    source: "posse-v2o",
  },
  {
    id: "povos-indigenas-povos-isolados",
    label: "povos isolados",
    office: "povos-indigenas",
    source: "posse-v2o",
  },
  {
    id: "povos-indigenas-direitos-dos-povos-indigenas",
    label: "direitos dos povos indígenas",
    office: "povos-indigenas",
    source: "posse-v2o",
  },
  {
    id: "relacoes-exteriores-politica-externa-e-diplomacia",
    label: "política externa e diplomacia",
    office: "relacoes-exteriores",
    source: "posse-v2o",
  },
  {
    id: "relacoes-exteriores-servicos-consulares",
    label: "serviços consulares",
    office: "relacoes-exteriores",
    source: "posse-v2o",
  },
  {
    id: "relacoes-exteriores-negociacoes-internacionais",
    label: "negociações internacionais",
    office: "relacoes-exteriores",
    source: "posse-v2o",
  },
  {
    id: "relacoes-exteriores-promocao-comercial-no-exterior",
    label: "promoção comercial no exterior",
    office: "relacoes-exteriores",
    source: "posse-v2o",
  },
  {
    id: "trabalho-e-emprego-emprego-e-renda",
    label: "emprego e renda",
    office: "trabalho-e-emprego",
    source: "posse-v2o",
  },
  {
    id: "trabalho-e-emprego-fiscalizacao-do-trabalho",
    label: "fiscalização do trabalho",
    office: "trabalho-e-emprego",
    source: "posse-v2o",
  },
  {
    id: "trabalho-e-emprego-registro-sindical",
    label: "registro sindical",
    office: "trabalho-e-emprego",
    source: "posse-v2o",
  },
  {
    id: "trabalho-e-emprego-economia-solidaria",
    label: "economia solidária",
    office: "trabalho-e-emprego",
    source: "posse-v2o",
  },
  {
    id: "trabalho-e-emprego-fgts-e-fat",
    label: "FGTS e FAT",
    office: "trabalho-e-emprego",
    source: "posse-v2o",
  },
  {
    id: "trabalho-e-emprego-politica-salarial",
    label: "política salarial",
    office: "trabalho-e-emprego",
    source: "posse-v2o",
  },
  {
    id: "transportes-rodovias-e-ferrovias",
    label: "rodovias e ferrovias",
    office: "transportes",
    source: "posse-v2o",
  },
  {
    id: "transportes-transito",
    label: "trânsito",
    office: "transportes",
    source: "posse-v2o",
  },
  {
    id: "transportes-concessoes-de-transporte-terrestre",
    label: "concessões de transporte terrestre",
    office: "transportes",
    source: "posse-v2o",
  },
  {
    id: "turismo-politica-de-turismo",
    label: "política de turismo",
    office: "turismo",
    source: "posse-v2o",
  },
  {
    id: "turismo-promocao-do-turismo",
    label: "promoção do turismo",
    office: "turismo",
    source: "posse-v2o",
  },
  {
    id: "turismo-credito-ao-turismo",
    label: "crédito ao turismo",
    office: "turismo",
    source: "posse-v2o",
  },
  {
    id: "controladoria-geral-da-uniao-auditoria-e-controle-interno",
    label: "auditoria e controle interno",
    office: "controladoria-geral-da-uniao",
    source: "posse-v2o",
  },
  {
    id: "controladoria-geral-da-uniao-combate-a-corrupcao",
    label: "combate à corrupção",
    office: "controladoria-geral-da-uniao",
    source: "posse-v2o",
  },
  {
    id: "controladoria-geral-da-uniao-transparencia-e-acesso-a-informacao",
    label: "transparência e acesso à informação",
    office: "controladoria-geral-da-uniao",
    source: "posse-v2o",
  },
  {
    id: "controladoria-geral-da-uniao-ouvidoria",
    label: "ouvidoria",
    office: "controladoria-geral-da-uniao",
    source: "posse-v2o",
  },
  {
    id: "controladoria-geral-da-uniao-correicao-de-servidores",
    label: "correição de servidores",
    office: "controladoria-geral-da-uniao",
    source: "posse-v2o",
  },
];
